
CREATE TABLE AGENTES (
  CODIGO               INTEGER NOT NULL ,
  EMPRESA              VARCHAR(3) NOT NULL  ,
  SERIE                VARCHAR(5) NOT NULL,
  NOMBRE               VARCHAR(40),
  PASSW                VARCHAR(10),
  FECHA_ALTA           DATE,
  FECHA_BAJA           DATE,
  ULTIMA_ACTUALIZACION TIMESTAMP,

  PRIMARY KEY ( CODIGO, EMPRESA )
);




CREATE TABLE "CABECERA_PEDIDO" 
(
  "NUMERO_CABECERA"	INTEGER NOT NULL,
  "SERIE"	VARCHAR(5) NOT NULL,
  "ALBARAN"	CHAR(1),
  "ANYO"	VARCHAR(5) NOT NULL,
  "CLASE"	CHAR(1),
  "CODIGO_CLIENTE"	INTEGER NOT NULL,
  "DTO_1"	DECIMAL(9, 0),
  "DTO_2"	DECIMAL(9, 0),
  "DTO_PP"	DECIMAL(9, 0),
  "FECHA"	TIMESTAMP,
  "OBSERVACIONES"	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
  "VERIFICADO"	CHAR(1),
  "TOTAL_IVA"	DECIMAL(15, 2),
 PRIMARY KEY ("NUMERO_CABECERA", "SERIE", "ANYO")
);
ALTER TABLE "CABECERA_PEDIDO" ADD FOREIGN KEY ("SERIE") REFERENCES AGENTES ("SERIE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "CABECERA_PEDIDO" ADD FOREIGN KEY ("CODIGO_CLIENTE") REFERENCES DPERSONALES ("CODIGO") ON UPDATE CASCADE ON DELETE CASCADE;




CREATE TABLE "LINEA_PEDIDO" 
(
  "NUMERO_LINEA"	INTEGER NOT NULL,
  "NUMERO_CABECERA"	INTEGER NOT NULL,
  "SERIE"	VARCHAR(5) NOT NULL,
  "CODIGO_ARTICULO"	VARCHAR(20),
  "TARIFAS"	SMALLINT,
  "CAJAS"	DECIMAL(9, 0),
  "UNIDADES"	DECIMAL(9, 0),
  "DTO_1"	DECIMAL(9, 0), 
  "DTO_2"	DECIMAL(9, 0),
  "DTO_3"	DECIMAL(9, 0),
  "OBSERVACIONES"	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
  "TOTAL"	DECIMAL(15, 4),
  "TOTAL_IVA"	DECIMAL(15, 4),
 PRIMARY KEY ("NUMERO_LINEA", "NUMERO_CABECERA", "SERIE")
);
ALTER TABLE "LINEA_PEDIDO" ADD FOREIGN KEY ("NUMERO_CABECERA", "SERIE" ) REFERENCES CABECERA_PEDIDO ("NUMERO_CABECERA", "SERIE") ON UPDATE CASCADE ON DELETE CASCADE;


CREATE TABLE "DPERSONALES" 
(
  "CODIGO"	INTEGER NOT NULL,
  "POTENCIAL"	CHAR(1),
  "FECHA_ALTA"	TIMESTAMP,
  "CODIGO2"	VARCHAR(15),
  "NOMBRE"	VARCHAR(40),
  "RAZON"	VARCHAR(40),
  "DIRECCION1"	VARCHAR(30),
  "DIRECCION2"	VARCHAR(30),
  "POBLACION"	VARCHAR(30),
  "PROVINCIA"	VARCHAR(30),
  "CONTACTO"	VARCHAR(40),
  "E_MAIL"	VARCHAR(40),
  "WEB"	VARCHAR(40),
  "NIF"	VARCHAR(15),
  "TELEFONO1"	VARCHAR(13),
  "TELEFONO2"	VARCHAR(13),
  "FAX"	VARCHAR(13),
  "COD_PAIS"	VARCHAR(3),
  "COD_POSTAL"	VARCHAR(10),
  "FECHA_BAJA"	DATE,
  "RUTA"	VARCHAR(5),
  "ZONA"	VARCHAR(5),
  "DIA_VISITA"	VARCHAR(20),
  "TIPO"	VARCHAR(5),
  "ACTIVIDAD"	VARCHAR(5),
  "AGENTE"	INTEGER,
  "FORMA_PAGO"	VARCHAR(5),
  "IVA_FIJO"	SMALLINT,
  "IRPF"	SMALLINT,
  "VERIFICADO"	CHAR(1),
  "ULTIMA_ACTUALIZACION"	TIMESTAMP,
 PRIMARY KEY ("CODIGO")
);


CREATE TABLE "COLA_EVENTOS" 
(
  "FECHA_HORA"	TIMESTAMP,
  "CODIGO"	INTEGER NOT NULL,
  "EXTRAS"	VARCHAR(200),
  "NUMERO"	INTEGER,
  "CLIENTE"	INTEGER
);
ALTER TABLE "COLA_EVENTOS" ADD FOREIGN KEY ("CODIGO") REFERENCES TIPO_MENSAJE ("CODIGO") ON UPDATE CASCADE ON DELETE CASCADE;


CREATE TABLE "TIPO_MENSAJE" 
(
  "CODIGO"	INTEGER NOT NULL,
  "DESCRIPCION"	VARCHAR(200),
 PRIMARY KEY ("CODIGO")
);


