/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Prev */

#ifndef _Included_Prev
#define _Included_Prev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Prev
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Prev_load
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
