/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class system_Cargador */

#ifndef _Included_system_Cargador
#define _Included_system_Cargador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     system_Cargador
 * Method:    a1
 * Signature: ()Ljavax/crypto/Cipher;
 */
JNIEXPORT jobject JNICALL Java_system_Cargador_a1
  (JNIEnv *, jobject);

/*
 * Class:     system_Cargador
 * Method:    a2
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_system_Cargador_a2
  (JNIEnv *, jobject);

/*
 * Class:     system_Cargador
 * Method:    a3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_system_Cargador_a3
  (JNIEnv *, jobject);

/*
 * Class:     system_Cargador
 * Method:    a4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_system_Cargador_a4
  (JNIEnv *, jobject);

/*
 * Class:     system_Cargador
 * Method:    a5
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_system_Cargador_a5
  (JNIEnv *, jobject);

/*
 * Class:     system_Cargador
 * Method:    get
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_system_Cargador_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
