/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class registry */

#ifndef _Included_registry
#define _Included_registry
#ifdef __cplusplus
extern "C" {
#endif
#undef registry_FOCUS_TRAVERSABLE_UNKNOWN
#define registry_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef registry_FOCUS_TRAVERSABLE_DEFAULT
#define registry_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef registry_FOCUS_TRAVERSABLE_SET
#define registry_FOCUS_TRAVERSABLE_SET 2L
#undef registry_TOP_ALIGNMENT
#define registry_TOP_ALIGNMENT 0.0f
#undef registry_CENTER_ALIGNMENT
#define registry_CENTER_ALIGNMENT 0.5f
#undef registry_BOTTOM_ALIGNMENT
#define registry_BOTTOM_ALIGNMENT 1.0f
#undef registry_LEFT_ALIGNMENT
#define registry_LEFT_ALIGNMENT 0.0f
#undef registry_RIGHT_ALIGNMENT
#define registry_RIGHT_ALIGNMENT 1.0f
#undef registry_serialVersionUID
#define registry_serialVersionUID -7644114512714619750i64
#undef registry_serialVersionUID
#define registry_serialVersionUID 4613797578919906343i64
#undef registry_INCLUDE_SELF
#define registry_INCLUDE_SELF 1L
#undef registry_SEARCH_HEAVYWEIGHTS
#define registry_SEARCH_HEAVYWEIGHTS 1L
#undef registry_OPENED
#define registry_OPENED 1L
#undef registry_serialVersionUID
#define registry_serialVersionUID 4497834738069338734i64
#undef registry_DEFAULT_CURSOR
#define registry_DEFAULT_CURSOR 0L
#undef registry_CROSSHAIR_CURSOR
#define registry_CROSSHAIR_CURSOR 1L
#undef registry_TEXT_CURSOR
#define registry_TEXT_CURSOR 2L
#undef registry_WAIT_CURSOR
#define registry_WAIT_CURSOR 3L
#undef registry_SW_RESIZE_CURSOR
#define registry_SW_RESIZE_CURSOR 4L
#undef registry_SE_RESIZE_CURSOR
#define registry_SE_RESIZE_CURSOR 5L
#undef registry_NW_RESIZE_CURSOR
#define registry_NW_RESIZE_CURSOR 6L
#undef registry_NE_RESIZE_CURSOR
#define registry_NE_RESIZE_CURSOR 7L
#undef registry_N_RESIZE_CURSOR
#define registry_N_RESIZE_CURSOR 8L
#undef registry_S_RESIZE_CURSOR
#define registry_S_RESIZE_CURSOR 9L
#undef registry_W_RESIZE_CURSOR
#define registry_W_RESIZE_CURSOR 10L
#undef registry_E_RESIZE_CURSOR
#define registry_E_RESIZE_CURSOR 11L
#undef registry_HAND_CURSOR
#define registry_HAND_CURSOR 12L
#undef registry_MOVE_CURSOR
#define registry_MOVE_CURSOR 13L
#undef registry_NORMAL
#define registry_NORMAL 0L
#undef registry_ICONIFIED
#define registry_ICONIFIED 1L
#undef registry_MAXIMIZED_HORIZ
#define registry_MAXIMIZED_HORIZ 2L
#undef registry_MAXIMIZED_VERT
#define registry_MAXIMIZED_VERT 4L
#undef registry_MAXIMIZED_BOTH
#define registry_MAXIMIZED_BOTH 6L
#undef registry_serialVersionUID
#define registry_serialVersionUID 2673458971256075116i64
#undef registry_EXIT_ON_CLOSE
#define registry_EXIT_ON_CLOSE 3L
/*
 * Class:     registry
 * Method:    getData
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_registry_getData
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
